config/routes.rb
Edi::Application.routes.draw do
  
  match '/clients/arvresult' => 'clients#arvresult' 
  match '/clients/phoneresult' => 'clients#phoneresult' 

  resources :client_medicals

  resources :appointments

  resources :clients

  resources :logins

  resources :users
  
  resources :sessions

  resources :items

  resources :sales

  resources :stocks


  root :to => "dashboard#index"
  
  match '/appointments/:id/destroy' => 'appointments#destroy'
  match '/users/:id/destroy' => 'users#destroy'
  match '/sales/:id/edit' => 'sales#destroy'
  match '/sales/:id' => 'sales#index'
  match '/stocks/:id' => 'stocks#index'
  match '/items/:id' => 'items#index'
  match '/sales/:id/destroy' => 'sales#destroy'
  match '/stocks/:id/destroy' => 'stocks#destroy'
  match '/items/:id/destroy' => 'items#destroy'
  match '/items/:id/merge' => 'items#merge'
  match '/items/new' => 'items#index'
  match '/items/price_list' => 'items#priceList'
  match '/users/:id' => 'users#show'
  match '/sessions/' => 'sessions#new'
  match '/sessions/new' => 'sessions#new'
  match '/sales' => 'sales#index'
  match '/report/perdiem' => 'report#perdiem'
  match '/sessions/destroy' => 'sessions#destroy'
  match '/report/range' => 'report#range'
  match '/report/range.pdf' => 'report#range'
  match '/report/stores' => 'report#stores'
  match '/report/remainder' => 'report#remainder'
  match '/report/salesgraph' => 'report#salesgraph'
  match '/items/duplicate' => 'items#duplicate'
  match '/items/merger' => 'items#merger' 
  match '/items/merged' => 'items#merged'
  

  get "clients/_form"

  get "clients/index"

  get "clients/show"

  get "clients/edit"

  get "report/index"

  get "report/show"
 
  get "items/duplicate"
 
  get "items/merger"

  post "items/merged"

  get "dashboard/index"

  get "items/itemslist"

  get "sessions/new"

  get "users/index"

  get "users/show"

  get "users/new"

  get "users/edit"
  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
  # unencrypted password
  attr_accessor :password

  # validation
  validates_presence_of      :first_name
  validates_presence_of      :surname
  validates_presence_of      :phone
  validates_length_of        :email, :within => 3..40
  validates_length_of        :password, :within => 6..40,
                                        :if => :password_required?
  validates_confirmation_of  :password, :if => :password_required?

  # callbacks
  before_save :encrypt_password

  # encrypts given password using salt
  def self.encrypt(pass, salt)
    Digest::SHA1.hexdigest("--#{salt}--#{pass}--")
  end

  protected
  
  # authenticate by email/password
  def self.authenticate(email, pass)
    user = find_by_email(email)
    user && user.authenticated?(pass) ? user : nil
  end  

  # does the given password match the stored encrypted password
  def authenticated?(pass)
   encrypted_password == User.encrypt(pass, salt)
  end

  #before save - create salt, encrypt password
  def encrypt_password
    return if password.blank?
    if new_record?
     self.salt = Digest::SHA1.hexdigest("--#{Time.now}--#{email}--")
    end
    self.encrypted_password = User.encrypt(password, salt)
  end

  #no encrypted password yet OR password attribute is set
  def password_required?
    encrypted_password.blank? || !password.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user, :except => [:index, :new, :create] 

  def index
    if logged_in?
    @users = User.find(:all, :order => "first_name")
    else
    redirect_to :controller => "sessions" , :action => "new"
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def new
    @user = User.new
  end

  def create
  @user = User.new(params[:user])

     if @user.save
        # @current_user = @user
        # session[:user] = @user.id

        flash[:notice] = "Successfully Signed up"
	redirect_to :action => "show", :id => @user.id
     else
        render :action => "new"
     end
  end  

  def edit
    @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
      
    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end



  private

  def find_user
   @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def image_for_admin_status(user)
    if user.admin?
      image_tag("star.gif", :alt => "Admin", size => "16x16")
    end
  end

end

app/views/users/_search.html.erb
<form action="/stocks" method="get" style="display:inline-block;width:400;">
<input type="text" name="search" placeholder="enter search item" autofocus="autofocus" />
<input type="hidden" name="selector" value="on" />
<input type="submit" value="search" />
</form>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<div class="form">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being created:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
  <legend>Edit <%=h @user.first_name %>'s Details</legend>
  <%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  
  <div class="field">
     <%= f.label :surname %><br />
     <%= f.text_field :surname %>
   </div>

   <div class="field">
     <%= f.label :email %><br />
     <%= f.text_field :email %>
   </div>

   <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
   </div>
   
   <div class="field">
    Administrator:
    <%= f.radio_button :admin, true %>
    <label for="user_admin_true" >Yes</label>
    <%= f.radio_button :admin, false %>
    <label for="user_admin_false" >No</label>
   </div>
   
   <div class="actions">
    <%= f.submit %>
  &nbsp;
   <%= link_to "cancel" , :action => "index" %>
  </div>
  <% end %>  
  </fieldset>
</div> 

app/views/users/index.html.erb
<h1>Showing Available Users</h1>


<ol class="list-deco">
 <% for user in @users %>
  <li>
    <%= link_to h(user.first_name + " " + user.surname ), :action => "show", :id => user.id %>
      
    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mobile:&nbsp;<%= h(user.phone) %>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;email:&nbsp;<%= h(user.email) %><span>
  </li>
 <% end %>
</ol>

<div id='yellow'><%= link_to "Add user", :controller => 'users', :action => 'new'  %></div>

app/views/users/new.html.erb
<h1>New User Registration</h1>

<div class="form">
    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being created:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<fieldset>
<legend>Create a Sellies ePOS Account</legend>
<%= form_for(@user) do |f| %>
   <div class="field">
     <%= f.label :first_name %><br />
     <%= f.text_field :first_name %>
   </div>

   <div class="field">
     <%= f.label :surname %><br />
     <%= f.text_field :surname %>
   </div>

   <div class="field">
     <%= f.label :email %><br />
     <%= f.text_field :email %>
   </div>

   <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
   </div>

   <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
   </div>

   <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
   </div>

   <%= submit_tag "Submit" %>
<% end %>
</fieldset>

</div>

app/views/users/show.html.erb
<h1><%= link_to "Users", :action => "index" %>
  &rarr; User Profile 
</h1>

<div class="details">
  <%= image_tag "dummy.png", :alt=> "profile", :class => "profile" %>
  <h2><%=h @user.first_name %>&nbsp;<%=h @user.surname %> </h2>
  <p>contact:&nbsp;<%=h @user.phone  %></p>
  <p><%=h @user.profile %></p>

  <div class="modify" >
    <%= link_to "edit details" , edit_user_path(@user) %> |
    <a href="/users/<%= @user.id %>/destroy" data-method="post" >delete user</a>
</div>
</div>