config/routes.rb
Edi::Application.routes.draw do
  
  match '/clients/arvresult' => 'clients#arvresult' 
  match '/clients/phoneresult' => 'clients#phoneresult' 

  resources :client_medicals

  resources :appointments

  resources :clients

  resources :logins

  resources :users
  
  resources :sessions

  resources :items

  resources :sales

  resources :stocks


  root :to => "dashboard#index"
  
  match '/appointments/:id/destroy' => 'appointments#destroy'
  match '/users/:id/destroy' => 'users#destroy'
  match '/sales/:id/edit' => 'sales#destroy'
  match '/sales/:id' => 'sales#index'
  match '/stocks/:id' => 'stocks#index'
  match '/items/:id' => 'items#index'
  match '/sales/:id/destroy' => 'sales#destroy'
  match '/stocks/:id/destroy' => 'stocks#destroy'
  match '/items/:id/destroy' => 'items#destroy'
  match '/items/:id/merge' => 'items#merge'
  match '/items/new' => 'items#index'
  match '/items/price_list' => 'items#priceList'
  match '/users/:id' => 'users#show'
  match '/sessions/' => 'sessions#new'
  match '/sessions/new' => 'sessions#new'
  match '/sales' => 'sales#index'
  match '/report/perdiem' => 'report#perdiem'
  match '/sessions/destroy' => 'sessions#destroy'
  match '/report/range' => 'report#range'
  match '/report/range.pdf' => 'report#range'
  match '/report/stores' => 'report#stores'
  match '/report/remainder' => 'report#remainder'
  match '/report/salesgraph' => 'report#salesgraph'
  match '/items/duplicate' => 'items#duplicate'
  match '/items/merger' => 'items#merger' 
  match '/items/merged' => 'items#merged'
  

  get "clients/_form"

  get "clients/index"

  get "clients/show"

  get "clients/edit"

  get "report/index"

  get "report/show"
 
  get "items/duplicate"
 
  get "items/merger"

  post "items/merged"

  get "dashboard/index"

  get "items/itemslist"

  get "sessions/new"

  get "users/index"

  get "users/show"

  get "users/new"

  get "users/edit"
  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  layout nil
  layout 'application', except: [:arvresult, :phoneresult]


  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])
    @appointment = Appointment.new
    @client_medical = ClientMedical.new
    @appointments = Appointment.all
    today = Date.today
    
    @appointments.each do |appointments|
	if appointments.due_date.to_date < today
		currentApp = Appointment.find(appointments.id)
		currentApp.update_attribute :status, 'done'
		currentApp.save
        elsif appointments.due_date.to_date > today
		currentApp = Appointment.find(appointments.id)
		currentApp.update_attribute :status, 'pending'
		currentApp.save
	end	
    end    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
      format.json { render json: @appointment }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :ok }
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_appointment.html.erb
<h2 style="font-size:22;">Enter appointment and dispensation data</h2>
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :client_id, :value => @client.id %>
  </div>
  <div class="field">
   <%= f.label :duration %>
   <%= f.number_field :duration %>
  </div>
  <div class="field">
   <label>Drugs taken in the morning (per day)</label>
   <%= f.number_field :taken_morning %>
  </div>
  <div class="field">
   <label>Drugs taken in the evening (per day)</label>
   <%= f.number_field :taken_evening %>
  </div>
  <div class="field">
    <label>Next appointment date</label>
    <input type="date" id="appointment_due_date" name="appointment[due_date]" / >
    </div>
  <div class="field">
   <%= f.hidden_field :created_by, :value => session[:user] %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit :class => 'more_button' %>
  </div>
<% end %>

app/views/clients/_editform.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :arv_number %>
    <%= f.text_field :arv_number %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.select(:gender, options_for_select(['Male', 'Female'])) %>
  </div>
  <div class="field">
    <%= f.label :education %>
    <%= f.select(:education, options_for_select(['Primary', 'Secondary', 'Tertiary'])) %>
  </div>
  <div class="field">
    <%= f.label :occupation %>
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :marital_status %>
     <%= f.select(:marital_status, options_for_select(['Single', 'Married', 'Divorced', 'Widowed'])) %>
  </div>
  <div class="field">
    <%= f.label :literacy_level %>
    <%= f.select(:literacy_level, options_for_select(['able to read', 'cannot read'])) %>
  </div>
  <div class="field">
    <label>Agreed to be involved in study</label>
    <%= f.radio_button :consent, true %>
    <label for="client_consent_true" >Yes</label>
    <%= f.radio_button :consent, false %>
    <label for="client_consent_false" >No</label>
  </div>
  <div class="actions">
    <%= f.submit :class => 'more_button' %>
  </div>
<% end %>

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :arv_number %>
    <%= f.text_field :arv_number %>
  </div>
  <div class="field">
    <%= f.label :patient_identifier %>
    <%= f.text_field :patient_identifier %>
  </div>
  <div class="field">
    <%= f.label :dob %>
    <input type="date" id="client_dob" name="client[dob]" / >
    
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.select(:gender, options_for_select(['Male', 'Female'])) %>
  </div>
  <div class="field">
    <%= f.label :education %>
    <%= f.select(:education, options_for_select(['Primary', 'Secondary', 'Tertiary'])) %>
  </div>
  <div class="field">
    <%= f.label :occupation %>
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :marital_status %>
     <%= f.select(:marital_status, options_for_select(['Single', 'Married', 'Divorced', 'Widowed'])) %>
  </div>
  <div class="field">
    <%= f.label :literacy_level %>
    <%= f.select(:literacy_level, options_for_select(['able to read', 'cannot read'])) %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <label>Agreed to be involved in study</label>
    <%= f.radio_button :consent, true %>
    <label for="client_consent_true" >Yes</label>
    <%= f.radio_button :consent, false %>
    <label for="client_consent_false" >No</label>
  </div>
  <div class="actions">
    <%= f.submit :class => 'more_button' %>
  </div>
<% end %>

app/views/clients/_medical.html.erb
<%= form_for(@client_medical) do |f| %>
  <% if @client_medical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client_medical.errors.count, "error") %> prohibited this client_medical from being saved:</h2>

      <ul>
      <% @client_medical.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :client_id, :value => @client.id %>
  </div>
  <div class="field">
    <label>Enrollment date</label>
    <input type="date" id="client_medical_enrollment_date" name="client_medical[enrollment_date]" / >
  </div>
  <div class="field">
    <%= f.label :regimen %>
    <%= f.select(:regimen, options_for_select(['0A', '0P', '1A', '1P', '2A',  '2P', '3A', '3P', '4A', '4P', '5A', '6A', '7A', '8A', '9A', 'non standard'])) %>
  </div>
  <div class="field">
    <label>Takes CPT</label>
    <%= f.select(:sulphur_allegy, options_for_select(['yes', 'no'])) %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit :class => 'more_button', :value => 'add' %>
  </div>
<% end %>

app/views/clients/_phone.html.erb
<form action="/clients" method="get" style="display:block;width:320px;">
<input type="hidden" name="selector" value="on" />
<input type="submit" value="search  by phone" id="phoner" style="display:inline-block;"/>
<input type="search" name="phone" id="phone_entry" placeholder="enter phone number" style="display:inline-block;" />
</form>

app/views/clients/_search.html.erb
<form action="/clients" method="get" style="display:block;width:320px;">
<input type="hidden" name="selector" value="on" />
<input type="submit" value="search  by arv number" id="searcher" style="display:inline-block;"/>
<input type="search" name="search" id="search_entry" placeholder="enter arv number" autofocus="autofocus" style="display:inline-block;" />
</form>

app/views/clients/arvresult.html.erb
<% search = params[:search] %>
<h1>Listing clients matching arv number: <%= search %></h1>
<table style="width:99%">
  <tr style="background:#fff;">
    <td style="font-weight:bold;">Arv number</td>
    <td style="font-weight:bold;">Date of Birth</td>
    <td style="font-weight:bold;">Gender</td>
    <td style="font-weight:bold;">Education</td>
    <td style="font-weight:bold;">Occupation</td>
    <td style="font-weight:bold;">Marital status</td>
    <td style="font-weight:bold;">Literacy level</td>
    <td style="font-weight:bold;">Phone</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<% 
    Client.find_by_sql(["SELECT * FROM edi.clients WHERE clients.arv_number LIKE ?", "%#{search}%"]).each do |client|
%>
<tr>
    <td>&nbsp;<%= client.arv_number %></td>
    <td><%= client.dob.to_date %></td>
    <td><%= client.gender %></td>
    <td><%= client.education %></td>
    <td><%= client.occupation %></td>
    <td><%= client.marital_status %></td>
    <td><%= client.literacy_level %></td>
    <td><%= client.phone %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
  </tr>
  <tr style="background:#fff;"><td style="background:#fff;" colspan="11">&nbsp;</td></tr>
<% end %>
</table>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'editform' %>

app/views/clients/index.html.erb
<script>
$(document).ready(function($){

$('#searcher').click(function(){
        var search = $("input#search_entry").val();

	$.ajax({ 
  	type: 'GET', 
  	url: '/clients', 
  	data: "search=" + search, 
 	success: function(data){
		$('#search_title').html('search results for:&nbsp;' + search);
		$('.clients').html('').load('/clients/arvresult?search=' + search);}
	}); 
	return false;
  });

$('#phoner').click(function(){
        var phone = $("input#phone_entry").val();

	$.ajax({ 
  	type: 'GET', 
  	url: '/clients', 
  	data: "phone=" + phone, 
 	success: function(data){
		$('#search_title').html('search results for:&nbsp;' + phone);
		$('.clients').html('').load('/clients/phoneresult?phone=' + phone);}
	}); 
	return false;
  });


});
</script>
<div style="display:inline-block">
<%= render :partial => 'search' %>
</div>
<span>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<span>
<div style="display:inline-block">
<%= render :partial => 'phone' %>
</div>
<div class="clients">
<%
	if params[:search].nil? 
%>
<h1>Listing clients</h1>
<table style="width:99%">
  <tr style="background:#fff;">
    <td style="font-weight:bold;">Arv number</td>
    <td style="font-weight:bold;">Date of Birth</td>
    <td style="font-weight:bold;">Gender</td>
    <td style="font-weight:bold;">Education</td>
    <td style="font-weight:bold;">Occupation</td>
    <td style="font-weight:bold;">Marital status</td>
    <td style="font-weight:bold;">Literacy level</td>
    <td style="font-weight:bold;">Phone</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<% @clients.each do |client| %>
  <tr>
    <td>&nbsp;<%= client.arv_number %></td>
    <td><%= client.dob.to_date %></td>
    <td><%= client.gender %></td>
    <td><%= client.education %></td>
    <td><%= client.occupation %></td>
    <td><%= client.marital_status %></td>
    <td><%= client.literacy_level %></td>
    <td><%= client.phone %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
  </tr>
  <tr style="background:#fff;"><td style="background:#fff;" colspan="11">&nbsp;</td></tr>
<% end %>
</table>
<%
    else
%>
<table style="width:99%">
  <tr style="background:#fff;">
    <td style="font-weight:bold;">Arv number</td>
    <td style="font-weight:bold;">Date of Birth</td>
    <td style="font-weight:bold;">Gender</td>
    <td style="font-weight:bold;">Education</td>
    <td style="font-weight:bold;">Occupation</td>
    <td style="font-weight:bold;">Marital status</td>
    <td style="font-weight:bold;">Literacy level</td>
    <td style="font-weight:bold;">Phone</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<% 
    search = params[:search]

    Client.find_by_sql(["SELECT * FROM edi.clients WHERE clients.arv_number LIKE ?", "%#{search}%"]).each do |client|
%>
<tr>
    <td>&nbsp;<%= client.arv_number %></td>
    <td><%= client.dob.to_date %></td>
    <td><%= client.gender %></td>
    <td><%= client.education %></td>
    <td><%= client.occupation %></td>
    <td><%= client.marital_status %></td>
    <td><%= client.literacy_level %></td>
    <td><%= client.phone %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
  </tr>
  <tr style="background:#fff;"><td style="background:#fff;" colspan="11">&nbsp;</td></tr>
<% end %>
</table>
<%
    end 
%>
</div>

app/views/clients/new.html.erb
<h2>New client</h2>

<%= render 'form' %>

app/views/clients/phoneresult.html.erb
<% phone = params[:phone] %>
<h1>Listing clients matching arv number: <%= phone %></h1>
<table style="width:99%">
  <tr style="background:#fff;">
    <td style="font-weight:bold;">Arv number</td>
    <td style="font-weight:bold;">Date of Birth</td>
    <td style="font-weight:bold;">Gender</td>
    <td style="font-weight:bold;">Education</td>
    <td style="font-weight:bold;">Occupation</td>
    <td style="font-weight:bold;">Marital status</td>
    <td style="font-weight:bold;">Literacy level</td>
    <td style="font-weight:bold;">Phone</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<% 
    Client.find_by_sql(["SELECT * FROM edi.clients WHERE clients.phone LIKE ?", "%#{phone}%"]).each do |client|
%>
<tr>
    <td>&nbsp;<%= client.arv_number %></td>
    <td><%= client.dob.to_date %></td>
    <td><%= client.gender %></td>
    <td><%= client.education %></td>
    <td><%= client.occupation %></td>
    <td><%= client.marital_status %></td>
    <td><%= client.literacy_level %></td>
    <td><%= client.phone %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
  </tr>
  <tr style="background:#fff;"><td style="background:#fff;" colspan="11">&nbsp;</td></tr>
<% end %>
</table>

app/views/clients/show.html.erb
<style>
#staff_right p{width:98%;}
</style>
<span id="notice"><%= notice %></span>
<div id="staff_right" style="height:250;">
<%
medical = ClientMedical.find(:first, :conditions => [ "client_id = ?", @client.id ], :limit => 1)

if !medical.nil?
         today = Date.today
	 status = 'pending'
	 appointment = Appointment.find(:first, :conditions => [ "status = ? AND client_id = ? ",  status, @client.id])

	if appointment.nil?
%>
	<%= render 'appointment' %>
<% 
	else
	months = Time.now.to_date - medical.enrollment_date.to_date 
	months = months / 30
%>
	<p>
	  <b>Duration of drugs to be taken on previous visit (days):</b><br /><br />
          <%= appointment.duration %>
	</p>
	<p>
         <b>Next appointment scheduled for:</b><br /><br />
	 <%= appointment.due_date.to_date.to_s(:long) %>
	</p>
	<p>
         <b>Months on ART:</b><br /><br />
	 <%= months.to_i %>
	</p>
<%
	end
        regimen = medical.regimen
        cpt = medical.sulphur_allegy
else
%>
	<%= render 'medical' %>
<%
end
%>
</div>
<div id="staff_right" style="height:200;top:290;overflow:auto;">
<h2 style="font-size:22;">Previous appointments</h2>
<%
	status = 'done'
	Appointment.find(:all, :conditions => [ "status = ? AND client_id = ? ",  status, @client.id]).each do |doneApp|
%>
	<p><%= doneApp.due_date.to_date.to_s(:long) %></p>
<%		
	end
%>
</div>
<p>
  <b>Arv Number:</b>
  <%= @client.arv_number %>
</p>

<p>
  <b>Date of Birth:</b>
  <%= @client.dob.to_date.to_s(:long) %>
</p>

<p>
  <b>Gender:</b>
  <%= @client.gender %>
</p>

<p>
  <b>Education:</b>
  <%= @client.education %>
</p>

<p>
  <b>Occupation:</b>
  <%= @client.occupation %>
</p>

<p>
  <b>Marital status:</b>
  <%= @client.marital_status %>
</p>

<p>
  <b>Literacy level:</b>
  <%= @client.literacy_level %>
</p>

<p>
  <b>Phone:</b>
  <%= @client.phone %>
</p>
<% if !medical.nil? %>
<p>
  <b>Regimen:</b>
  <%= regimen %>
</p>
<p>
 <b>Takes CPT:</b>
 <%= cpt %>
</p>
<% end %>
<p>
  <b>Agrees to study:</b>
  <%= @client.consent.to_s %>
</p>