config/routes.rb
Edi::Application.routes.draw do
  
  match '/clients/arvresult' => 'clients#arvresult' 
  match '/clients/phoneresult' => 'clients#phoneresult' 

  resources :client_medicals

  resources :appointments

  resources :clients

  resources :logins

  resources :users
  
  resources :sessions

  resources :items

  resources :sales

  resources :stocks


  root :to => "dashboard#index"
  
  match '/appointments/:id/destroy' => 'appointments#destroy'
  match '/users/:id/destroy' => 'users#destroy'
  match '/sales/:id/edit' => 'sales#destroy'
  match '/sales/:id' => 'sales#index'
  match '/stocks/:id' => 'stocks#index'
  match '/items/:id' => 'items#index'
  match '/sales/:id/destroy' => 'sales#destroy'
  match '/stocks/:id/destroy' => 'stocks#destroy'
  match '/items/:id/destroy' => 'items#destroy'
  match '/items/:id/merge' => 'items#merge'
  match '/items/new' => 'items#index'
  match '/items/price_list' => 'items#priceList'
  match '/users/:id' => 'users#show'
  match '/sessions/' => 'sessions#new'
  match '/sessions/new' => 'sessions#new'
  match '/sales' => 'sales#index'
  match '/report/perdiem' => 'report#perdiem'
  match '/sessions/destroy' => 'sessions#destroy'
  match '/report/range' => 'report#range'
  match '/report/range.pdf' => 'report#range'
  match '/report/stores' => 'report#stores'
  match '/report/remainder' => 'report#remainder'
  match '/report/salesgraph' => 'report#salesgraph'
  match '/items/duplicate' => 'items#duplicate'
  match '/items/merger' => 'items#merger' 
  match '/items/merged' => 'items#merged'
  

  get "clients/_form"

  get "clients/index"

  get "clients/show"

  get "clients/edit"

  get "report/index"

  get "report/show"
 
  get "items/duplicate"
 
  get "items/merger"

  post "items/merged"

  get "dashboard/index"

  get "items/itemslist"

  get "sessions/new"

  get "users/index"

  get "users/show"

  get "users/new"

  get "users/edit"
  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/client_medical.rb
class ClientMedical < ActiveRecord::Base
end

app/controllers/client_medicals_controller.rb
class ClientMedicalsController < ApplicationController
  # GET /client_medicals
  # GET /client_medicals.json
  def index
    @client_medicals = ClientMedical.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @client_medicals }
    end
  end

  # GET /client_medicals/1
  # GET /client_medicals/1.json
  def show
    @client_medical = ClientMedical.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client_medical }
    end
  end

  # GET /client_medicals/new
  # GET /client_medicals/new.json
  def new
    @client_medical = ClientMedical.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client_medical }
    end
  end

  # GET /client_medicals/1/edit
  def edit
    @client_medical = ClientMedical.find(params[:id])
  end

  # POST /client_medicals
  # POST /client_medicals.json
  def create
    @client_medical = ClientMedical.new(params[:client_medical])

    respond_to do |format|
      if @client_medical.save
        format.html { redirect_to @client_medical, notice: 'Client medical was successfully created.' }
        format.json { render json: @client_medical, status: :created, location: @client_medical }
      else
        format.html { render action: "new" }
        format.json { render json: @client_medical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /client_medicals/1
  # PUT /client_medicals/1.json
  def update
    @client_medical = ClientMedical.find(params[:id])

    respond_to do |format|
      if @client_medical.update_attributes(params[:client_medical])
        format.html { redirect_to @client_medical, notice: 'Client medical was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @client_medical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_medicals/1
  # DELETE /client_medicals/1.json
  def destroy
    @client_medical = ClientMedical.find(params[:id])
    @client_medical.destroy

    respond_to do |format|
      format.html { redirect_to client_medicals_url }
      format.json { head :ok }
    end
  end
end

app/helpers/client_medicals_helper.rb
module ClientMedicalsHelper
end

app/views/client_medicals/_form.html.erb
<%= form_for(@client_medical) do |f| %>
  <% if @client_medical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client_medical.errors.count, "error") %> prohibited this client_medical from being saved:</h2>

      <ul>
      <% @client_medical.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br />
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :regimen %><br />
    <%= f.text_field :regimen %>
  </div>
  <div class="field">
    <%= f.label :sulphur_allegy %><br />
    <%= f.text_field :sulphur_allegy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/client_medicals/edit.html.erb
<h1>Editing client_medical</h1>

<%= render 'form' %>

<%= link_to 'Show', @client_medical %> |
<%= link_to 'Back', client_medicals_path %>

app/views/client_medicals/index.html.erb
<h1>Listing client_medicals</h1>

<table>
  <tr>
    <th>Client</th>
    <th>Regimen</th>
    <th>Sulphur allegy</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @client_medicals.each do |client_medical| %>
  <tr>
    <td><%= client_medical.client_id %></td>
    <td><%= client_medical.regimen %></td>
    <td><%= client_medical.sulphur_allegy %></td>
    <td><%= link_to 'Show', client_medical %></td>
    <td><%= link_to 'Edit', edit_client_medical_path(client_medical) %></td>
    <td><%= link_to 'Destroy', client_medical, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client medical', new_client_medical_path %>

app/views/client_medicals/new.html.erb
<h1>New client_medical</h1>

<%= render 'form' %>

<%= link_to 'Back', client_medicals_path %>

app/views/client_medicals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Client:</b>
  <%= @client_medical.client_id %>
</p>

<p>
  <b>Regimen:</b>
  <%= @client_medical.regimen %>
</p>

<p>
  <b>Sulphur allegy:</b>
  <%= @client_medical.sulphur_allegy %>
</p>


<%= link_to 'Edit', edit_client_medical_path(@client_medical) %> |
<%= link_to 'Back', client_medicals_path %>