config/routes.rb
Edi::Application.routes.draw do
  
  match '/clients/arvresult' => 'clients#arvresult' 
  match '/clients/phoneresult' => 'clients#phoneresult' 

  resources :client_medicals

  resources :appointments

  resources :clients

  resources :logins

  resources :users
  
  resources :sessions

  resources :items

  resources :sales

  resources :stocks


  root :to => "dashboard#index"
  
  match '/appointments/:id/destroy' => 'appointments#destroy'
  match '/users/:id/destroy' => 'users#destroy'
  match '/sales/:id/edit' => 'sales#destroy'
  match '/sales/:id' => 'sales#index'
  match '/stocks/:id' => 'stocks#index'
  match '/items/:id' => 'items#index'
  match '/sales/:id/destroy' => 'sales#destroy'
  match '/stocks/:id/destroy' => 'stocks#destroy'
  match '/items/:id/destroy' => 'items#destroy'
  match '/items/:id/merge' => 'items#merge'
  match '/items/new' => 'items#index'
  match '/items/price_list' => 'items#priceList'
  match '/users/:id' => 'users#show'
  match '/sessions/' => 'sessions#new'
  match '/sessions/new' => 'sessions#new'
  match '/sales' => 'sales#index'
  match '/report/perdiem' => 'report#perdiem'
  match '/sessions/destroy' => 'sessions#destroy'
  match '/report/range' => 'report#range'
  match '/report/range.pdf' => 'report#range'
  match '/report/stores' => 'report#stores'
  match '/report/remainder' => 'report#remainder'
  match '/report/salesgraph' => 'report#salesgraph'
  match '/items/duplicate' => 'items#duplicate'
  match '/items/merger' => 'items#merger' 
  match '/items/merged' => 'items#merged'
  

  get "clients/_form"

  get "clients/index"

  get "clients/show"

  get "clients/edit"

  get "report/index"

  get "report/show"
 
  get "items/duplicate"
 
  get "items/merger"

  post "items/merged"

  get "dashboard/index"

  get "items/itemslist"

  get "sessions/new"

  get "users/index"

  get "users/show"

  get "users/new"

  get "users/edit"
  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/application.html.erb
<!DOCTYPE html">
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<html lang="en">

<head>
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>MPH project</title>
<%= stylesheet_link_tag 'jquery-ui.css' %>
<%= stylesheet_link_tag 'default.css', :media => 'all' %>
<%= stylesheet_link_tag 'perfect-scrollbar.css', :media => 'all' %>
<% 
  user = User.find(session[:user])
  if !user.admin?
%>
<%= stylesheet_link_tag 'user.css', :media => 'all' %>
<% end %>
<%= javascript_include_tag 'jquery.js' %>
<%= javascript_include_tag 'jquery.min.js' %>
<%= javascript_include_tag 'perfect-scrollbar.js' %>
<%= javascript_include_tag 'application' %><title>Sellies ePOS</title>
<%= stylesheet_link_tag 'jquery-ui.css' %>
<%= stylesheet_link_tag 'default.css', :media => 'all' %>
<%= stylesheet_link_tag 'perfect-scrollbar.css', :media => 'all' %>
<% 
  user = User.find(session[:user])
  if !user.admin?
%>
<%= stylesheet_link_tag 'user.css', :media => 'all' %>
<% end %>
<%= javascript_include_tag 'jquery.js' %>
<%= javascript_include_tag 'jquery.min.js' %>
<%= javascript_include_tag 'perfect-scrollbar.js' %>
<%= javascript_include_tag 'application.js' %>
</head>
<script type="text/javascript">
$(document).ready(function() {
	//sales range report
        $('#appointmentDate').hide();

	$('#appbydate').click(function(){
        	$('#appointmentDate').show();		
	});
});
</script>
<style>
/*#right-panel a{color:#145b80;}*/
#main_content{overflow:hidden;height:550px;}
#left-panel{position:relative;display:block;width:98.5%;height:550;overflow:auto}
#logo{
	margin:0;
	padding:0;
	position:absolute;
	left:100px;
	top:-23px;
    }
#logo img{width:100;height:100;}
#header_name{
	top:0px;
	margin:0;
	padding:0;
	position:absolute;
	left:235px;
	width:700px;
	}
#main_menu{top:108}
#main_body{top:15}
#main_footer{
	top:20;
	margin:0 auto;
	width:1024;
	height:20;
	overflow:hidden;
}
form input[type="text"]{width:300;}
form input[type="password"]{width:300;}
</style>
<body>
<div id="appointmentDate" style="position:absolute;z-index:10000;width:100%;height:720px;background-color: rgba(10, 10, 10, 0.5);">
<form action="/appointments" method="get" style="position:absolute;top:200px;left:500px;width:150px;background:#fff;padding:30px;">
<label style="color:#000;font-weight:strong;width:150px;text-align:center;">Start Date</label><br />
<input type="date" id="start_date" name="start_date" /><br />
<label style="color:#000;font-weight:strong;width:150px;text-align:center;">End Date</label><br />
<input type="date" id="end_date" name="end_date" /><br /> 
<input type="submit" value="proceed" id="submit" style="width:150.5px;margin-top:1px;" />
</form>
</div>
<div id="main_menu">
<div class="cssMenu">
<ul>
    <li id="plus">&nbsp;</li>
    <li><a href="/">Home</a></li>
	<li><a href="#">Clients</a>
	<ul>
	    <li><%= link_to 'new', new_client_path %></li>
	    <li><a href="/clients">view all</a></li>
	</ul>
	</li> 
    <li><a href="#">Appointments</a>
	<ul>
	    <li><a href="#" id="appbydate">view by date</a></li>
	    <li><a href="/appointments">view all</a></li>
	</ul>
    </li>
    <li><a href="#">Users</a>
	<!-- <ul>
	    <li><a href="add_user_view.php">upload user</a></li>
	    <li><a href="add_publication_view.php">upload publication</a></li>
	    <li><a href="show_users_view.php">users list</a></li>
	    <li><a href="show_publication_view.php">publications list</a></li>
	</ul> -->
    </li>
   <li id="minus" style="width:465px">&nbsp;</li>
</ul>
</div>
</div>
<div id="content">
<div id="main_header">
<div id="logo">
	  
	  </div>
<div id="header_name">
<span>Mobile Based ART Support system</span>
</div>
<div id="top-header" style="top:50">
<span>
<% if logged_in? %>
    <%= link_to "logout", :controller => "sessions",
                          :action     => "destroy" %>
<% end %>
</span>
</div>
</div>
<div id="main_body">
<div id="main_content">
<div id="container1"> 
<div id="left-panel">
<%= yield %>
</div>
</div>
</div>

</div>
</div>
</div>
<div id="main_footer">
<div id="footer-holder">   
<span id="footer-left">
		<!-- <a target="_blank" href="http://www.google.com/+MwaiMtingwi" style="margin-left:10;">prowess apps</a> -->   
</span>
<span id="footer-mid">
	
</span>
<span id="footer-right">
		 <!-- <p>&copy BICO <?php echo date('Y'); ?>. All rights reserved</p> -->		  
</span>
</div>
</div>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html">
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<html lang="en">

<head>
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>MPH project</title>
<%= stylesheet_link_tag 'default.css', :media => 'all' %>
<%= stylesheet_link_tag 'dashboard.css', :media => 'all' %>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>
</head>
<style>
/*#right-panel a{color:#145b80;}*/
#main_content{overflow:hidden;height:500px;}
#left-panel{position:relative;display:inline-block;width:780;}
#logo{
	margin:0;
	padding:0;
	position:absolute;
	left:100px;
	top:-23px;
    }
#logo img{width:100;height:100;}
#header_name{
	top:0px;
	margin:0;
	padding:0;
	position:absolute;
	left:235px;
	width:700px;
	}
#main_menu{top:108}
#main_body{top:15}
#main_footer{
	top:20;
	margin:0 auto;
	width:1024;
	height:20;
	overflow:hidden;
	}
#main_header{top:30;}
#top-header{top:55;z-index:500;}
#index_cars_list{
	z-index:600;
	top:50;
	padding-left:10;
	position:absolute;
        display:block;
        width:980;
	height:400;
	border:1px dotted #000;
	background:#fff;
	border-radius:10px;
	overflow:auto;
	}
#staff_left{
	padding:0;
	z-index:600;
	top:50;
	padding-left:10;
	position:absolute;
        display:block;
        width:450;
	height:424;
	border:1px dotted #000;
	background:#f2f1f0;
	border-radius:10px;
	overflow:hidden;
	}
#staff_right{
	z-index:600;
	top:50;
	left:500;
	padding:10;
	position:absolute;
        display:block;
        width:480;
	height:405;
	border:1px dotted #000;
	background:#fff;
	border-radius:10px;
	overflow:auto;
	}
#staff_right #box{
	margin-top:20;
	padding:5;
	background: #F9F8FE;
	border:1px dotted #0F0941;
	display:block;
	width:97%;
	font:17px/1 “helvetica neue”, helvetica, arial, sans-serif;
	}
#staff_left #box{
	margin-top:20;
	padding:5;
	background: #F9F8FE;
	border:1px dotted #0F0941;
	display:block;
	width:97%;
	font:17px/1 “helvetica neue”, helvetica, arial, sans-serif;
	}
#car_close a{
	position:absolute;
	top:370;
	left:880;
	display:block;
	background-color: #fff;
	border: 1px solid #3f4fd2;
	border-radius: 5px;
	padding: 3px 35px 3px 35px;
    	text-decoration: none;
    	color: #3f4fd2;
    	font:13px Comic Sans MS, "cursive";
    	text-align: center;
	}
#car_close a:active{border: 2px solid #3f4fd2;}
#booking_close{
	position:absolute;
	top:440;
	left:340;
	z-index:700;
	}
#booking_close a{
	position:relative;
	display:block;
	background-color: #fff;
	border: 1px solid #3f4fd2;
	border-radius: 5px;
	padding: 3px 35px 3px 35px;
    	text-decoration: none;
    	color: #3f4fd2;
    	font:13px Comic Sans MS, "cursive";
    	text-align: center;
	}
#booking_close a:active{border: 2px solid #3f4fd2;}
#noti_close{
	position:absolute;
	top:440;
	left:870;
	z-index:700;
	}
#noti_close a{
	position:relative;
	display:block;
	background-color: #fff;
	border: 1px solid #3f4fd2;
	border-radius: 5px;
	padding: 3px 35px 3px 35px;
    	text-decoration: none;
    	color: #3f4fd2;
    	font:13px Comic Sans MS, "cursive";
    	text-align: center;
	}
#noti_close a:active{border: 2px solid #3f4fd2;}
#notifier ol{
	position:relative;
	display:block;
	height:auto;
	width:100%;
	counter-reset: li;
	list-style: none;
	*list-style: decimal;

	font: 14px "Trebuchet MS", Arial, Helvetica, sans-serif;
	padding: 0;
	margin-bottom: 4em;
	}
#notifier ol ol{
	margin: 0 0 0 2em;
	}
#notifier ol li{
	display:block;
	height:20;
	margin-top:20;
	}
#staff_left ol{
	position:relative;
	display:block;
	height:auto;
	width:100%;
	counter-reset: li;
	list-style: none;
	*list-style: decimal;
	font: 14px "Trebuchet MS", Arial, Helvetica, sans-serif;
	padding: 0;
	margin-bottom: 4em;
	}
#staff_left ol ol{
	margin: 0 0 0 2em;
	}
#staff_left ol li{
	display:block;
	height:20;
	margin-top:20;
	}
.list-deco a{
	width:375;
	position: relative;
	height:20;
	display: block;
	padding: .4em .4em .4em .8em;
	*padding: .4em;
	margin: .5em 0 .5em 2.5em;
	background: #ddd;
	color: #444;
	text-decoration: none;
	transition: all .3s ease-out;		
	}
.list-deco a:hover{
	background: #eee;
	}
.list-deco a:before{
	content: counter(li);
	counter-increment: li;
	position: absolute;
	left: -2.5em;
	top: 50%;
	margin-top: -1em;
	background: #87ceeb;
	height: 2em;
	width: 2em;
	line-height: 2em;
	text-align: center;
	font-weight: bold;
	}
.list-deco a:after{
	position: absolute;
	content: '';
	border: .5em solid transparent;
	left: -1em;
	top: 50%;
	margin-top: -.5em;
	transition: all .3s ease-out;
	}
.list-deco a:hover:after{
	left: -.5em;
	border-left-color: #87ceeb;
	}
</style>
<body>

<div id="main_menu">
<div class="cssMenu" style="visibility:hidden;">
<ul>
    <li id="plus">&nbsp;</li>		 
    <li id="plus" style="border-radius:0;width:610;border:none;margin-left:-5;">&nbsp;</li>	
    <li id="minus" style="width:258px;margin-left:-5;">&nbsp;</li>
</ul>
</div>
</div>
<div id="content">
<div id="main_header">
<div id="top-header">
<span>
<% if logged_in? %>
    <%= link_to "logout", :controller => "sessions",
                          :action     => "destroy" %>
<% end %>
</span>
</div>
<div id="logo">
	  
	  </div>
<div id="header_name">
<span>Mobile Based ART Support system</span>
</div>
</div>
<div id="main_body">
<div id="main_content">
<div id="container1"> 
<div id="left-panel" style="width:990;">
<span style="color:green"><%= flash[:notice] %></span>
<%= yield %>
</div>

</div>
</div>
</div>
<div id="main_footer">
<div id="footer-holder">   
<span id="footer-left">
		<!-- <a target="_blank" href="http://www.google.com/+MwaiMtingwi" style="margin-left:10;">prowess apps</a> -->   
</span>
<span id="footer-mid">
	
</span>
<span id="footer-right">
		  <!-- <p>&copy Standard Bank <?php echo date('Y'); ?>. All rights reserved</p> -->		  
</span>
</div>
</div>
</body>
</html>


app/views/layouts/report.html.erb
<html>
<head>
<title>Sellies ePOS</title>
<%= stylesheet_link_tag 'default.css', :media => 'all' %>
<%= stylesheet_link_tag 'perfect-scrollbar.css' %>
<%= javascript_include_tag 'jquery.min.js' %>
<%= javascript_include_tag 'jquery.js' %>
<%= javascript_include_tag 'perfect-scrollbar.js' %>
  <%= csrf_meta_tag %>
</head>
<style>

@media print {
body{background:#fff;}
#info{background:#fff;}
.report{
	width:1000;
	position:relative;
        top:10;
	height:650;
	background:#fff;
 	padding-left:10px;
        overflow:visible;
        font:11px/18px "Trebuchet MS", Arial, Helvetica, sans-serif;
	}

.report table{width:100%;}
.report table td #head{
	margin:0;
	padding:0;
	font-weight:strong;
	color:#adafb1;
	text-align:center;
	display:inline-block;
	font:19px/18px "Trebuchet MS", Arial, Helvetica, sans-serif;	
	}
#yellow{visibility:hidden;}
#info table #blank{
	background: #fff;
      }
}
</style> 
<body>


<div id="content">
<%= yield %>
</div>
<div id='yellow'><%= link_to "finish", :controller => 'report', :action => 'index'  %></div>
</body>
</html>

app/views/layouts/sessions.html.erb
<html>
<head>
<title>MPH Project</title>
<%= stylesheet_link_tag 'login.css', :media => 'all' %>
<%= javascript_include_tag 'default.js' %>
  <%= csrf_meta_tag %>
</head>
 
<body>

<div id="login"> 
<%= yield %>
</div>

</body>
</html>